### ISSUE TITLE
add the ability to set the upper/lower bounds in the random function

### ISSUE THREAD

**Issue by HardWare68** [HardWare68/CollabDiscordBot#8]
that sounds like it'd be smart

**Comment by BlaisinX** [comment]
the upper and lower bounds can be manually set by 
message.channel.send(Math.floor(Math.random() * UPPER BOUND MINUS LOWER BOUND) + LOWER BOUND);

**Comment by HardWare68** [comment]
but like, once we make it as a function, we could pass it as arguments to the function, and then it would be super smart and cool and everyone on github would be like "wow thats so smart"

**Comment by BlaisinX** [comment]
yeah okay

**Comment by HardWare68** [comment]
you want me to make the function and all that fun stuff

**Comment by BlaisinX** [comment]
I'm not sure how to, so yeah

**Comment by HardWare68** [comment]
okay dokay artichokay

**Comment by BlaisinX** [comment]
I misspoke, it's
message.channel.send(Math.floor(Math.random() * UPPER BOUND PLUS LOWER BOUND) + LOWER BOUND);

**Comment by BlaisinX** [comment]
minus one
